version: '3'
services:
  app:
    build: .
    image: mozamimy/telescreen
    environment:
      DEST_CHANNEL: general
      API_KEY:
    command:
      - render
      - /app/config.yml
      - --
      - /app/telescreen
      - -c
      - /app/config.yml
      - -a
      - $API_KEY
